title: Danny Hubert # My name (& website title)
logo: "/images/logo.jpg?raw=true" # my headshot photo
description: > # links below
  <br><br>
  <a href="https://www.linkedin.com/in/dmhubert/">LinkedIn</a> 
  <br>
  <a href="https://drive.google.com/file/d/1yT-v8oHi27ipzWFWQMTq9QyQRntvzyvg/view?usp=drive_link" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/dannyhubert9/">GitHub</a>  
  
theme: jekyll-theme-minimal
